version: '3.9'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: numeroly-postgres
    environment:
      POSTGRES_USER: numeroly
      POSTGRES_PASSWORD: password
      POSTGRES_DB: numeroly
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U numeroly"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - numeroly-network

  # Redis Cache
  redis:
    image: redis:7.2-alpine
    container_name: numeroly-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - numeroly-network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  numeroly-network:
    driver: bridge
